export type Curse = {
  name: string;
  type: string;
  grade: string;
  effect: string;
  trigger: string;
  breakCondition: string;
  origin: string;
  sideEffects: string;
};

export const curseDatabase: Curse[] = [
  {
    name: "Toque do Esquecimento",
    type: "Mental",
    grade: "Médio",
    effect: "A cada dia, a vítima perde uma memória importante. Começa com memórias recentes e avança para as mais antigas. Após 30 dias, esquece a própria identidade.",
    trigger: "Ser tocado por uma criatura das sombras durante a lua nova.",
    breakCondition: "Recuperar todas as memórias enfrentando a criatura em seu plano de origem.",
    origin: "Necromancia das Sombras",
    sideEffects: "Lapsos repentinos, confusão, perda de reconhecimento facial.",
  },
  {
    name: "Pele de Vidro",
    type: "Física",
    grade: "Alto",
    effect: "A pele da vítima torna-se translúcida como vidro. Recebe o dobro de dano de ataques físicos e qualquer queda causa dano crítico.",
    trigger: "Ingerir uma poção preparada durante um eclipse solar.",
    breakCondition: "Banhar-se no sangue de um elemental de terra puro.",
    origin: "Alquimia Corrompida",
    sideEffects: "Fragilidade óssea, hemorragias internas espontâneas.",
  },
  {
    name: "Maldição do Eco",
    type: "Comunicação",
    grade: "Baixo",
    effect: "Todas as palavras da vítima são repetidas três vezes em volume crescente. Não consegue furtividade nem discrição.",
    trigger: "Quebrar um juramento feito em local sagrado.",
    breakCondition: "Completar uma jornada de silêncio absoluto por 7 dias.",
    origin: "Magia Arcana",
    sideEffects: "Danos nas cordas vocais, zumbido constante.",
  },
  {
    name: "Sombra Invertida",
    type: "Espiritual",
    grade: "Alto",
    effect: "A sombra da vítima ganha vida própria e tenta sabotá-la. Revela segredos, move objetos, apaga tochas.",
    trigger: "Atravessar um véu dimensional sem permissão.",
    breakCondition: "Capturar a própria sombra em um recipiente de prata.",
    origin: "Plano das Sombras",
    sideEffects: "Fotossensibilidade, insônia, paranoia.",
  },
  {
    name: "Fome Eterna",
    type: "Fisiológica",
    grade: "Médio",
    effect: "Fome insaciável. Nenhum alimento satisfaz. Perde 1 de Constituição por semana. Pode comer coisas não comestíveis.",
    trigger: "Comer a carne de uma criatura amaldiçoada.",
    breakCondition: "Jejuar por 30 dias usando um amuleto de purificação.",
    origin: "Maldição Ancestral",
    sideEffects: "Obsessão por comida, autofagia em estágios avançados.",
  },
  {
    name: "Olhos do Passado",
    type: "Visual",
    grade: "Médio",
    effect: "Visões do passado se sobrepõem ao presente. Difícil distinguir realidade de memória. Revela segredos históricos involuntariamente.",
    trigger: "Olhar diretamente para um artefato temporal.",
    breakCondition: "Testemunhar um evento histórico crucial e intervir corretamente.",
    origin: "Cronomancia",
    sideEffects: "Enxaquecas, desorientação temporal, crises epilépticas.",
  },
  {
    name: "Peso da Culpa",
    type: "Mental",
    grade: "Médio",
    effect: "Objetos ao redor tornam-se cada vez mais pesados para a vítima. Carregar a própria mochila torna-se exaustivo.",
    trigger: "Trair um companheiro de forma irreversível.",
    breakCondition: "Realizar um sacrifício genuíno para salvar a pessoa traída.",
    origin: "Magia da Consciência",
    sideEffects: "Depressão profunda, isolamento social.",
  },
  {
    name: "Voz das Bestas",
    type: "Comunicação",
    grade: "Baixo",
    effect: "Perde a fala humana e só consegue se comunicar com animais. Animais a tratam como igual.",
    trigger: "Ser mordido por um lobo durante a lua cheia.",
    breakCondition: "Convencer um rei animal a levantar a maldição.",
    origin: "Licantropia Menor",
    sideEffects: "Grunhidos involuntários, unhas afiadas.",
  },
  {
    name: "Murcha da Vida",
    type: "Fisiológica",
    grade: "Alto",
    effect: "A vítima envelhece 1 ano a cada semana. A pele resseca, o cabelo cai. Redução permanente de atributos físicos.",
    trigger: "Fazer um pacto com um espírito da morte.",
    breakCondition: "Transferir os anos perdidos para um receptáculo vivo.",
    origin: "Necromancia Avançada",
    sideEffects: "Cheiro de decomposição, atração de insetos.",
  },
  {
    name: "Geada Interior",
    type: "Elemental",
    grade: "Médio",
    effect: "O corpo da vítima produz frio extremo. Objetos ao redor congelam. Não pode usar fogo ou entrar em locais quentes.",
    trigger: "Ser amaldiçoado por um elemental de gelo moribundo.",
    breakCondition: "Derreter o coração congelado em lava de vulcão ativo.",
    origin: "Plano Elemental do Gelo",
    sideEffects: "Hipotermia crônica, dormência nas extremidades.",
  },
  {
    name: "Escrita Amaldiçoada",
    type: "Escrita",
    grade: "Baixo",
    effect: "Tudo que a vítima escreve se torna realidade. Mentiras escritas viram verdades. Rabiscos acidentais podem criar objetos.",
    trigger: "Usar uma pena de corvo amaldiçoada para escrever.",
    breakCondition: "Escrever a própria absolvição em um pergaminho celestial.",
    origin: "Magia de Tinta",
    sideEffects: "Mãos manchadas permanentemente, papel queima ao toque.",
  },
  {
    name: "Mãos do Caçador",
    type: "Física",
    grade: "Baixo",
    effect: "Armas grudam nas mãos da vítima. Não pode largar armas voluntariamente. Dorme e come com a arma empunhada.",
    trigger: "Matar um inocente com as próprias mãos.",
    breakCondition: "Entregar a arma voluntariamente a quem perdoou o crime.",
    origin: "Maldição de Guerra",
    sideEffects: "Cãibras, tendinite, ossos dos dedos se fundem.",
  },
  {
    name: "Sede de Saber",
    type: "Mental",
    grade: "Alto",
    effect: "Insaciável curiosidade mágica. A vítima é forçada a ler todo livro, examinar todo objeto mágico. Pode revelar segredos perigosos.",
    trigger: "Ler um grimório proibido sem proteção.",
    breakCondition: "Apagar todo conhecimento proibido da própria mente.",
    origin: "Conhecimento Amaldiçoado",
    sideEffects: "Alucinações com vozes de entidades, perda de sanidade.",
  },
  {
    name: "Pés de Chumbo",
    type: "Física",
    grade: "Baixo",
    effect: "A vítima fica mais pesada a cada passo. Velocidade reduzida em 50%. Não pode correr, pular ou escalar.",
    trigger: "Amaldiçoado por um anão da montanha.",
    breakCondition: "Dançar sobre uma bigorna encantada por 7 horas.",
    origin: "Magia da Terra",
    sideEffects: "Afundamento em terrenos moles, dificuldade para nadar.",
  },
  {
    name: "Choro Constante",
    type: "Emocional",
    grade: "Baixo",
    effect: "A vítima chora incontrolavelmente. Lágrimas ácidas queimam a pele. Visão embaralhada pelo choro constante.",
    trigger: "Perder algo amado de forma trágica.",
    breakCondition: "Rir genuinamente por 1 hora sem parar.",
    origin: "Maldição Emocional",
    sideEffects: "Desidratação, irritação nos olhos, depressão.",
  },
  {
    name: "Troca de Sortes",
    type: "Destino",
    grade: "Alto",
    effect: "A sorte da vítima se inverte. Sucessos viram fracassos. Moedas sempre caem no lado errado. Aliados viram rivais.",
    trigger: "Ganhar uma aposta com um ser do destino.",
    breakCondition: "Realizar uma boa ação que não traga benefício algum.",
    origin: "Tece-las do Destino",
    sideEffects: "Paranoia, medo de tomar decisões.",
  },
  {
    name: "Espectro Faminto",
    type: "Espiritual",
    grade: "Épico",
    effect: "Um espectro segue a vítima e devora suas emoções positivas. Alegria vira apatia, amor vira indiferença. O espectro fica mais forte a cada emoção consumida.",
    trigger: "Sobreviver a uma experiência de quase-morte em local amaldiçoado.",
    breakCondition: "Sacrificar uma memória feliz para alimentar o espectro até ele partir.",
    origin: "Plano Etéreo",
    sideEffects: "Anedonia, perda de conexão com entes queridos.",
  },
  {
    name: "Dedos da Trapaça",
    type: "Física",
    grade: "Médio",
    effect: "A vítima não consegue segurar nada com firmeza. Objetos escorregam das mãos. Não pode empunhar armas ou usar ferramentas.",
    trigger: "Roubar de um templo sagrado.",
    breakCondition: "Devolver em triplo tudo que foi roubado na vida.",
    origin: "Maldição dos Ladrões",
    sideEffects: "Mãos sempre suadas, tremores finos.",
  },
  {
    name: "Mal do Sono",
    type: "Fisiológica",
    grade: "Médio",
    effect: "A vítima dorme a qualquer momento. Sonecas involuntárias de 1d4 horas. Não acorda com barulho, só com dano.",
    trigger: "Ser picado por uma criatura dos sonhos.",
    breakCondition: "Ficar acordado por 7 dias consecutivos.",
    origin: "Plano dos Sonhos",
    sideEffects: "Pesadelos vívidos, sonambulismo, falar dormindo segredos.",
  },
  {
    name: "Couro de Árvore",
    type: "Física",
    grade: "Médio",
    effect: "A pele endurece e vira casca de árvore. +5 de armadura natural, mas -2 de destreza. Vulnerável a fogo (dano dobrado).",
    trigger: "Dormir sob uma árvore amaldiçoada em noite de lua cheia.",
    breakCondition: "Banhar-se na seiva de uma árvore da vida.",
    origin: "Maldição da Floresta",
    sideEffects: "Ramos crescem dos dedos, fotossíntese necessária.",
  },
  {
    name: "Olhar Petrificante",
    type: "Visual",
    grade: "Épico",
    effect: "Tudo que a vítima olha por mais de 3 segundos começa a petrificar. Criaturas pequenas viram pedra em 1 minuto. A própria vítima petrifica lentamente.",
    trigger: "Olhar nos olhos de uma Medusa refletida em um espelho.",
    breakCondition: "Chorar lágrimas de uma estátua que foi amada.",
    origin: "Criaturas Antigas",
    sideEffects: "Olhos viram pedra, piscar doloroso, visão dupla.",
  },
  {
    name: "Azia Arcana",
    type: "Magia",
    grade: "Baixo",
    effect: "Sempre que lança uma magia, a vítima tem azia severa. Gases, arrotos e dores estomacais. Magias podem falhar se a azia for forte.",
    trigger: "Comer comida de um caldeirão de bruxa.",
    breakCondition: "Beber uma poção de hortelã abençoada por 30 dias.",
    origin: "Magia Culinária",
    sideEffects: "Mau hálito mágico, cheiro de enxofre ao arrotar.",
  },
];

export const curseTypes = [...new Set(curseDatabase.map((c) => c.type))];
export const curseGrades = [...new Set(curseDatabase.map((c) => c.grade))];