export type CurseGrade = "Grau 4" | "Grau 3" | "Grau 2" | "Grau 1" | "Grau Especial" | "Maldição de Dispersão"
export type CurseType = "Natural" | "Medo" | "Vingativa" | "Artificial" | "Híbrida" | "Ancestral" | "Conceitual"

export interface Curse {
  name: string
  grade: CurseGrade
  type: CurseType
  nd: number
  effect: string
  trigger: string
  breakCondition: string
  origin: string
  sideEffects: string[]
  domain?: string
  techniques?: string[]
}

export const FULL_CURSES: Curse[] = [
  {
    name: "Maldição do Espelho",
    grade: "Grau 4",
    type: "Medo",
    nd: 3,
    effect: "Ao olhar para a vítima no espelho, o reflexo ganha vida e tenta puxar a vítima para dentro do espelho.",
    trigger: "A vítima olhar para seu próprio reflexo",
    breakCondition: "Quebrar o espelho ou fazer o reflexo voltar ao normal",
    origin: "Medo de perder a própria identidade ou se olhar no espelho no escuro",
    sideEffects: ["Medo de espelhos", "O rosto da vítima parece diferente no reflexo", "Objetos ao redor se quebram facilmente"],
    techniques: ["Reflexo Distorcido", "Aprisionamento no Espelho"],
  },
  {
    name: "Piada Sem Graça",
    grade: "Grau 4",
    type: "Medo",
    nd: 2,
    effect: "Faz a vítima rir incontrolavelmente até não conseguir respirar.",
    trigger: "Ouvir uma piada sem graça ou situação cômica constrangedora",
    breakCondition: "A vítima parar de rir por 1 minuto completo",
    origin: "Medo de ser ridicularizado em público",
    sideEffects: ["Riso nervoso em momentos inadequados", "Dificuldade para falar sério"],
  },
  {
    name: "Maldição do Pesadelo",
    grade: "Grau 3",
    type: "Natural",
    nd: 5,
    effect: "Impede a vítima de dormir, causando alucinações e exaustão.",
    trigger: "Ficar acordado após as 3h da manhã",
    breakCondition: "Dormir por 8 horas ininterruptas",
    origin: "Medo de ter pesadelos ou insônia crônica",
    sideEffects: ["Olheiras profundas", "Alucinações com olhos vermelhos", "Sono REM extremamente vívido"],
  },
  {
    name: "Vazio Interior",
    grade: "Grau 2",
    type: "Conceitual",
    nd: 8,
    effect: "Drena a energia emocional da vítima, tornando-a apática e sem vontade própria.",
    trigger: "A vítima experimentar uma forte emoção positiva",
    breakCondition: "Experimentar uma emoção genuína que conecte a vítima a outra pessoa",
    origin: "Sensação de vazio existencial e falta de propósito",
    sideEffects: ["Dificuldade de sentir emoções", "Olhar vidrado e distante", "Perda de interesse em hobbies"],
    techniques: ["Dreno Emocional", "Aura de Apatia"],
  },
  {
    name: "Mãos Invisíveis",
    grade: "Grau 3",
    type: "Medo",
    nd: 6,
    effect: "Mãos espectrais tocam a vítima quando ela está sozinha, causando arrepios e paralisia.",
    trigger: "Ficar sozinho em um ambiente silencioso e escuro",
    breakCondition: "Passar uma noite inteira acompanhado",
    origin: "Medo de fantasmas ou do escuro",
    sideEffects: ["Sensação constante de estar sendo observado", "Calafrios frequentes"],
  },
  {
    name: "Maldição do Esquecimento",
    grade: "Grau 3",
    type: "Natural",
    nd: 5,
    effect: "A vítima esquece progressivamente momentos importantes de sua vida.",
    trigger: "A vítima estar em um local familiar mas não reconhecer",
    breakCondition: "Recriar uma memória importante com a ajuda de alguém próximo",
    origin: "Medo de desenvolver Alzheimer ou perda de memória",
    sideEffects: ["Dificuldade de reconhecer rostos", "Confusão mental frequente"],
    techniques: ["Toque do Esquecimento"],
  },
  {
    name: "Pele de Pedra",
    grade: "Grau 2",
    type: "Natural",
    nd: 9,
    effect: "A pele da vítima endurece lentamente, tornando-se imóvel e insensível.",
    trigger: "A vítima ser tocada por uma pessoa que não toca há muito tempo",
    breakCondition: "Receber um abraço genuíno de alguém que ama",
    origin: "Medo de perder o toque humano ou carência afetiva",
    sideEffects: ["Perda de tato nas áreas afetadas", "Dificuldade de se mover", "Pele escurece e racha"],
    techniques: ["Petrificação", "Golpe Pedregoso"],
  },
  {
    name: "Maldição da Gula",
    grade: "Grau 2",
    type: "Natural",
    nd: 8,
    effect: "Faz a vítima sentir fome incontrolável que nunca é saciada.",
    trigger: "Comer qualquer alimento",
    breakCondition: "Ficar 24 horas sem comer nada",
    origin: "Medo de passar fome ou transtorno alimentar",
    sideEffects: ["Ganho de peso extremo", "Dores de estômago constantes", "Obsessão por comida"],
  },
  {
    name: "Sussurros do Desprezo",
    grade: "Grau 2",
    type: "Vingativa",
    nd: 7,
    effect: "Vozes sussurram insultos e críticas sobre a vítima o tempo todo.",
    trigger: "A vítima sofrer uma crítica ou humilhação pública",
    breakCondition: "A vítima se aceitar plenamente ou confrontar a origem dos sussurros",
    origin: "Vingança de uma pessoa que foi humilhada publicamente e se tornou maldição",
    sideEffects: ["Baixa autoestima", "Paranoia social", "Isolamento voluntário"],
  },
  {
    name: "Maldição do Tempo",
    grade: "Grau 1",
    type: "Ancestral",
    nd: 12,
    effect: "Envelhece a vítima rapidamente sempre que ela sente ansiedade.",
    trigger: "A vítima se preocupar com o futuro",
    breakCondition: "Aceitar o ciclo natural da vida ou usar energia amaldiçoada para reverter o processo",
    origin: "Medo ancestral do envelhecimento e da morte",
    sideEffects: ["Cabelos brancos prematuros", "Rugas profundas", "Dores nas articulações"],
    techniques: ["Aceleração Temporal", "Toque do Tempo"],
  },
  {
    name: "Sombra Devoradora",
    grade: "Grau 1",
    type: "Medo",
    nd: 12,
    effect: "A sombra da vítima ganha vida e tenta consumir seu corpo.",
    trigger: "Estar em um local com iluminação direta que projeta sombra",
    breakCondition: "Destruir a fonte de luz ou fazer a sombra retornar ao normal",
    origin: "Medo do desconhecido que espreita nas sombras",
    sideEffects: ["Medo de locais escuros", "A sombra parece se mover sozinha", "Paralisia do sono"],
    techniques: ["Consumir Sombra", "Projeção de Sombra"],
  },
  {
    name: "Maldição da Multidão",
    grade: "Grau 1",
    type: "Medo",
    nd: 11,
    effect: "Em lugares lotados, a vítima vê rostos distorcidos e ameaçadores.",
    trigger: "Estar em um local com mais de 20 pessoas",
    breakCondition: "Ficar sozinho por 1 hora",
    origin: "Fobia social extrema",
    sideEffects: ["Agorafobia", "Suor frio em locais públicos", "Ataques de pânico"],
  },
  {
    name: "Maldição do Aprendiz",
    grade: "Grau 1",
    type: "Vingativa",
    nd: 13,
    effect: "Faz a vítima esquecer progressivamente o que aprendeu sobre jujutsu.",
    trigger: "Usar uma técnica amaldiçoada",
    breakCondition: "Redescobrir o conhecimento com a ajuda de um mestre",
    origin: "Vingança de um aprendiz que foi traído por seu mestre",
    sideEffects: ["Frustração constante", "Perda de confiança em si mesmo", "Dificuldade de aprender coisas novas"],
    techniques: ["Dreno de Conhecimento", "Apagão Mental"],
  },
  {
    name: "Maldição do Amor Não Correspondido",
    grade: "Grau 2",
    type: "Vingativa",
    nd: 9,
    effect: "Faz a vítima sentir uma dor física intensa ao ver o objeto de seu amor.",
    trigger: "Ver a pessoa amada",
    breakCondition: "Declarar seus sentimentos e ser aceito ou rejeitado definitivamente",
    origin: "Vingança de alguém que morreu com o coração partido",
    sideEffects: ["Coração acelera perigosamente", "Lágrimas de sangue em casos extremos", "Obsessão crescente"],
    techniques: ["Dor Compartilhada", "Vínculo Coração"],
  },
  {
    name: "Maldição do Palhaço",
    grade: "Grau 3",
    type: "Medo",
    nd: 4,
    effect: "Faz a vítima ver palhaços em todos os lugares, rindo ameaçadoramente.",
    trigger: "Ver a imagem de um palhaço (TV, desenho, fantasia)",
    breakCondition: "Enfrentar um palhaço real e perceber que não há perigo",
    origin: "Medo de palhaços (coulrofobia)",
    sideEffects: ["Pesadelos com palhaços", "Evitar circos e festas infantis", "Risos alucinatórios"],
  },
  {
    name: "Maldição do Abandono",
    grade: "Grau 2",
    type: "Natural",
    nd: 8,
    effect: "Pessoas próximas à vítima sentem um desejo irracional de se afastar.",
    trigger: "Formar um vínculo emocional forte com alguém",
    breakCondition: "A vítima passar um dia inteiro sem ver ninguém que ama",
    origin: "Medo de ser abandonado por quem ama",
    sideEffects: ["Solidão", "Dificuldade de fazer amigos", "Amigos se afastam sem explicação"],
    techniques: ["Aura de Repulsa", "Corte de Vínculo"],
  },
  {
    name: "Maldição do Julgamento",
    grade: "Grau 1",
    type: "Conceitual",
    nd: 15,
    effect: "A vítima vê olhos em todos os lugares, julgando cada ação sua.",
    trigger: "Cometer um erro ou falha moral perante outros",
    breakCondition: "Aceitar que errar é humano e perdoar a si mesmo",
    origin: "Medo de ser julgado e condenado pela sociedade",
    sideEffects: ["Ansiedade social severa", "Perfeccionismo doentio", "Crise de identidade"],
    techniques: ["Olhos do Julgador", "Peso da Culpa"],
  },
  {
    name: "Maldição Aquática",
    grade: "Grau 3",
    type: "Natural",
    nd: 5,
    effect: "A vítima sente que está se afogando mesmo fora d'água.",
    trigger: "Água tocando o rosto da vítima",
    breakCondition: "Aprender a nadar ou superar o medo de água",
    origin: "Medo de se afogar ou trauma aquático na infância",
    sideEffects: ["Medo de chuva", "Falta de ar em banhos", "Evita beber água em público"],
  },
  {
    name: "Maldição do Fracasso",
    grade: "Grau 3",
    type: "Natural",
    nd: 6,
    effect: "Tudo que a vítima tenta fazer dá errado de forma cômica e trágica.",
    trigger: "Tentar algo novo ou desafiador",
    breakCondition: "Suceder em uma tarefa importante sozinho",
    origin: "Medo do fracasso e da inadequação",
    sideEffects: ["Frustração constante", "Zombaria dos outros", "Desistência fácil"],
  },
  {
    name: "Maldição do Silêncio",
    grade: "Grau 2",
    type: "Vingativa",
    nd: 10,
    effect: "Absorve todo som ao redor da vítima, deixando-a em silêncio absoluto.",
    trigger: "A vítima tentar pedir ajuda ou gritar",
    breakCondition: "A vítima se comunicar efetivamente sem usar a voz",
    origin: "Vingança de alguém que foi ignorado em vida e nunca pôde se expressar",
    sideEffects: ["Surdez temporária", "Isolamento social", "Comunicação por sinais"],
    techniques: ["Bolha de Silêncio", "Grito Silencioso"],
  },
  {
    name: "Maldição da Perfeição",
    grade: "Grau 1",
    type: "Conceitual",
    nd: 14,
    effect: "Faz a vítima ver defeitos em tudo e todos, nunca estando satisfeita.",
    trigger: "Observar algo imperfeito ou assimétrico",
    breakCondition: "Aceitar a imperfeição como parte natural da vida",
    origin: "Medo da imperfeição e da mediocridade",
    sideEffects: ["TOC severo", "Dificuldade de se relacionar", "Insatisfação crônica"],
    techniques: ["Correção Forçada", "Olhos da Crítica"],
  },
  {
    name: "Maldição da Solidão Eterna",
    grade: "Grau Especial",
    type: "Conceitual",
    nd: 20,
    effect: "Isola a vítima em uma dimensão paralela vazia por tempo indeterminado.",
    trigger: "A vítima se sentir completamente sozinha mesmo acompanhada",
    breakCondition: "Uma conexão genuína com outra pessoa romper a barreira dimensional",
    origin: "Medo primordial da solidão absoluta, amplificado por séculos de sofrimento",
    sideEffects: ["Trauma de isolamento", "Dificuldade de confiar em outros", "Síndrome do pânico ao ficar sozinho"],
    techniques: ["Dimensão do Vazio", "Barreira do Isolamento", "Laço Quebrado"],
  },
  {
    name: "Maldição da Dor Fantasma",
    grade: "Grau 2",
    type: "Vingativa",
    nd: 9,
    effect: "A vítima sente dores de ferimentos que nunca sofreu.",
    trigger: "Ver alguém se ferir",
    breakCondition: "A vítima enfrentar a causa da dor original",
    origin: "Vingança de alguém que morreu em agonia extrema",
    sideEffects: ["Cicatrizes emocionais", "Medo de ver sangue", "Dores fantasmas recorrentes"],
    techniques: ["Transferência de Dor", "Agonia Compartilhada"],
  },
  {
    name: "Maldição do Vampiro Emocional",
    grade: "Grau 2",
    type: "Híbrida",
    nd: 10,
    effect: "Drena a energia vital de pessoas próximas, deixando-as exaustas.",
    trigger: "Ficar perto de pessoas felizes ou energéticas",
    breakCondition: "A vítima aprender a controlar sua absorção de energia",
    origin: "Pessoa que se sentia drenada por interações sociais e se tornou uma maldição",
    sideEffects: ["Pessoas ao redor ficam cansadas", "A vítima se sente culpada", "Isolamento social"],
    techniques: ["Absorção Vital", "Campo de Exaustão"],
  },
  {
    name: "Maldição do Labirinto",
    grade: "Grau 1",
    type: "Natural",
    nd: 12,
    effect: "Cria um labirinto mental na mente da vítima, fazendo-a se perder mesmo em lugares conhecidos.",
    trigger: "Entrar em um lugar com muitas portas ou corredores",
    breakCondition: "Encontrar uma saída com a ajuda de alguém de confiança",
    origin: "Medo de se perder ou ficar preso em lugares confinados",
    sideEffects: ["Claustrofobia", "Medo de elevadores", "Sempre se perder em lugares novos"],
    techniques: ["Labirinto Mental", "Portas Infinitas"],
  },
  {
    name: "Maldição da Culpa",
    grade: "Grau 1",
    type: "Conceitual",
    nd: 13,
    effect: "Manifesta fisicamente a culpa da vítima, criando ferimentos proporcionais à gravidade do erro.",
    trigger: "A vítima sentir culpa por algo que fez",
    breakCondition: "A vítima se perdoar ou fazer as pazes com seu erro",
    origin: "Medo da culpa e do remorso eterno",
    sideEffects: ["Cicatrizes misteriosas", "Pesadelos com o erro cometido", "Paranoia sobre machucados"],
    techniques: ["Ferida da Consciência", "Peso do Remorso"],
  },
  {
    name: "Maldição do Tempo Perdido",
    grade: "Grau Especial",
    type: "Ancestral",
    nd: 22,
    effect: "Prende a vítima em um loop temporal no pior momento de sua vida.",
    trigger: "A vítima pensar em seu maior arrependimento",
    breakCondition: "Aceitar o passado e seguir em frente genuinamente",
    origin: "Medo coletivo do arrependimento e do 'e se'",
    sideEffects: ["Trauma revivido constantemente", "Dificuldade de viver o presente", "Crises de déjà-vu"],
    techniques: ["Loop Temporal", "Aprisionamento no Passado", "Ressonância do Arrependimento"],
  },
  {
    name: "Maldição do Jogador",
    grade: "Grau 3",
    type: "Natural",
    nd: 6,
    effect: "Faz a vítima sentir necessidade compulsiva de apostar e jogar.",
    trigger: "Ver dinheiro ou itens de valor",
    breakCondition: "Ficar 1 mês sem apostar ou jogar",
    origin: "Medo da ruína financeira e vício em jogos",
    sideEffects: ["Perda de dinheiro", "Mentiras constantes", "Dívidas acumuladas"],
  },
  {
    name: "Maldição da Doença",
    grade: "Grau 2",
    type: "Natural",
    nd: 9,
    effect: "Enfraquece o sistema imunológico da vítima, deixando-a constantemente doente.",
    trigger: "Exposição a qualquer germe ou mudança de temperatura",
    breakCondition: "Ficar completamente saudável por 1 mês sem tratamento mágico",
    origin: "Medo de doenças e da fragilidade do corpo",
    sideEffects: ["Doenças frequentes", "Fadiga crônica", "Internações hospitalares"],
    techniques: ["Toque Pestilento", "Aura de Doença"],
  },
  {
    name: "Maldição da Paranoia",
    grade: "Grau 3",
    type: "Natural",
    nd: 5,
    effect: "Faz a vítima desconfiar de todos ao seu redor, vendo conspirações em tudo.",
    trigger: "Alguém fazer algo de bom para a vítima sem motivo aparente",
    breakCondition: "Confiar em alguém e não ser traído",
    origin: "Medo de ser traído ou enganado",
    sideEffects: ["Isolamento social", "Afastamento de amigos", "Crise de confiança"],
  },
  {
    name: "Maldição das Alturas",
    grade: "Grau 4",
    type: "Medo",
    nd: 3,
    effect: "Faz a vítima sentir tontura e vertigem mesmo em lugares baixos.",
    trigger: "Olhar para baixo de qualquer altura acima de 2 metros",
    breakCondition: "Enfrentar uma altura significativa e superar o medo",
    origin: "Medo de altura (acrofobia)",
    sideEffects: ["Tontura frequente", "Evitar escadas e janelas", "Náusea em sacadas"],
  },
  {
    name: "Maldição da Morte",
    grade: "Grau Especial",
    type: "Ancestral",
    nd: 25,
    effect: "Manifesta uma entidade que persegue a vítima constantemente, causando acidentes fatais ao redor.",
    trigger: "A vítima estar em perigo iminente de morte",
    breakCondition: "Enfrentar a própria mortalidade e aceitá-la",
    origin: "Medo universal da morte, acumulado por milênios",
    sideEffects: ["Visões de morte", "Acidentes frequentes", "Pessoas ao redor morrem em acidentes"],
    techniques: ["Toque da Morte", "Ceifador Manifestado", "Aura Mortal"],
  },
  {
    name: "Maldição da Inveja",
    grade: "Grau 2",
    type: "Natural",
    nd: 8,
    effect: "Faz a vítima sentir inveja doentia de todos ao redor.",
    trigger: "Ver alguém com algo que a vítima não tem",
    breakCondition: "A vítima conseguir algo que deseja por mérito próprio",
    origin: "Medo de nunca ser bom o suficiente ou ter o suficiente",
    sideEffects: ["Amargura constante", "Relações tóxicas", "Infelicidade crônica"],
    techniques: ["Olho Invejoso", "Dreno de Sorte"],
  },
  {
    name: "Maldição do Escuridão",
    grade: "Grau 1",
    type: "Ancestral",
    nd: 16,
    effect: "Engole toda a luz ao redor da vítima, criando uma escuridão absoluta e aterrorizante.",
    trigger: "O pôr do sol",
    breakCondition: "Atravessar uma noite inteira sem luz alguma e manter a sanidade",
    origin: "Medo primordial do escuro, transmitido por gerações",
    sideEffects: ["Cegueira noturna", "Pesadelos vívidos", "Sensação de presença no escuro"],
    techniques: ["Manto de Escuridão", "Toque Sombrio", "Olhos na Escuridão"],
  },
  {
    name: "Maldição da Rejeição",
    grade: "Grau 3",
    type: "Natural",
    nd: 4,
    effect: "Faz a vítima sentir uma dor aguda no peito sempre que é rejeitada.",
    trigger: "Ser rejeitado ou ignorado por alguém",
    breakCondition: "A vítima se aceitar independentemente da opinião alheia",
    origin: "Medo da rejeição social e do abandono",
    sideEffects: ["Baixa autoconfiança", "Evitar interações sociais", "Sensibilidade extrema a críticas"],
  },
  {
    name: "Maldição do Segredo",
    grade: "Grau 2",
    type: "Vingativa",
    nd: 10,
    effect: "Faz a vítima revelar seus segredos mais profundos involuntariamente.",
    trigger: "Alguém fazer uma pergunta direta para a vítima",
    breakCondition: "A vítima não ter mais segredos a esconder",
    origin: "Vingança de alguém que guardou um segredo até a morte",
    sideEffects: ["Vergonha constante", "Perda de privacidade", "Dificuldade de confiar nos outros"],
    techniques: ["Confissão Forçada", "Verdade Irresistível"],
  },
]
